build:
	docker build . -t cr.yandex/crpcad5uhlb7oh89ja0v/potencial-frontend
push:
	docker push cr.yandex/crpcad5uhlb7oh89ja0v/potencial-frontend
run:
	docker run --detach --rm --name potencial-frontend -p 8000:8000 cr.yandex/crpcad5uhlb7oh89ja0v/potencial-frontend
stop:
	docker stop potencial-frontend